/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountManagement: typeof import('./src/components/dashboard/account_information/AccountManagement.vue')['default']
    AllTask: typeof import('./src/components/dashboard/all_task/AllTask.vue')['default']
    AllTaskLive: typeof import('./src/components/dashboard/all_task/AllTaskLive.vue')['default']
    ChooseTask: typeof import('./src/components/dashboard/create_task/ChooseTask.vue')['default']
    ClipResultCard: typeof import('./src/components/card/ClipResultCard.vue')['default']
    CreateCaption: typeof import('./src/components/dashboard/CreateCaption.vue')['default']
    CreateTask: typeof import('./src/components/dashboard/create_task/CreateTask.vue')['default']
    CreateTaskLive: typeof import('./src/components/dashboard/create_task/CreateTaskLive.vue')['default']
    CreateVideo: typeof import('./src/components/dashboard/CreateVideo.vue')['default']
    DashboardSiderBar: typeof import('./src/components/bar/DashboardSiderBar.vue')['default']
    FooterBar: typeof import('./src/components/bar/FooterBar.vue')['default']
    HeaderBar: typeof import('./src/components/bar/HeaderBar.vue')['default']
    HomeCard: typeof import('./src/components/card/HomeCard.vue')['default']
    IAntDesignDollarOutlined: typeof import('~icons/ant-design/dollar-outlined')['default']
    IFluentApps16Regular: typeof import('~icons/fluent/apps16-regular')['default']
    IGridiconsCaption: typeof import('~icons/gridicons/caption')['default']
    IPhMoonBold: typeof import('~icons/ph/moon-bold')['default']
    IPhSunBold: typeof import('~icons/ph/sun-bold')['default']
    IPhUser: typeof import('~icons/ph/user')['default']
    IPhVideo: typeof import('~icons/ph/video')['default']
    IQuillVip: typeof import('~icons/quill/vip')['default']
    LogIn: typeof import('./src/components/dashboard/account_information/LogIn.vue')['default']
    NewTask: typeof import('./src/components/dashboard/NewTask.vue')['default']
    NewVue: typeof import('./src/components/dashboard/NewVue.vue')['default']
    PayMoney: typeof import('./src/components/dashboard/payment/PayMoney.vue')['default']
    PayResult: typeof import('./src/components/dashboard/payment/PayResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignModal: typeof import('./src/components/modal/SignModal.vue')['default']
    TaskCard: typeof import('./src/components/card/TaskCard.vue')['default']
    TaskCenter: typeof import('./src/components/dashboard/task_center/TaskCenter.vue')['default']
    TaskDetail: typeof import('./src/components/dashboard/task_detail/TaskDetail.vue')['default']
    TaskDetailLive: typeof import('./src/components/dashboard/task_detail/TaskDetailLive.vue')['default']
    UserInformation: typeof import('./src/components/card/UserInformation.vue')['default']
    UserPersona: typeof import('./src/components/dashboard/UserPersona.vue')['default']
    UserProfile: typeof import('./src/components/dashboard/account_information/UserProfile.vue')['default']
    UserTransaction: typeof import('./src/components/card/UserTransaction.vue')['default']
    VideoCredit: typeof import('./src/components/dashboard/task_center/VideoCredit.vue')['default']
    VideoDelivery: typeof import('./src/components/dashboard/task_center/VideoDelivery.vue')['default']
    VideoResource: typeof import('./src/components/dashboard/task_center/VideoResource.vue')['default']
  }
}
