/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllTask: typeof import('./src/components/dashboard/AllTask.vue')['default']
    AllTaskLive: typeof import('./src/components/dashboard/AllTaskLive.vue')['default']
    ChooseTask: typeof import('./src/components/dashboard/ChooseTask.vue')['default']
    ClipResultCard: typeof import('./src/components/card/ClipResultCard.vue')['default']
    CreateCaption: typeof import('./src/components/dashboard/CreateCaption.vue')['default']
    CreateTask: typeof import('./src/components/dashboard/CreateTask.vue')['default']
    CreateTaskLive: typeof import('./src/components/dashboard/CreateTaskLive.vue')['default']
    CreateVideo: typeof import('./src/components/dashboard/CreateVideo.vue')['default']
    DashboardSiderBar: typeof import('./src/components/bar/DashboardSiderBar.vue')['default']
    FooterBar: typeof import('./src/components/bar/FooterBar.vue')['default']
    HeaderBar: typeof import('./src/components/bar/HeaderBar.vue')['default']
    HomeCard: typeof import('./src/components/card/HomeCard.vue')['default']
    IAntDesignDollarOutlined: typeof import('~icons/ant-design/dollar-outlined')['default']
    IFluentApps16Regular: typeof import('~icons/fluent/apps16-regular')['default']
    IGridiconsCaption: typeof import('~icons/gridicons/caption')['default']
    IPhMoonBold: typeof import('~icons/ph/moon-bold')['default']
    IPhSunBold: typeof import('~icons/ph/sun-bold')['default']
    IPhUser: typeof import('~icons/ph/user')['default']
    IPhVideo: typeof import('~icons/ph/video')['default']
    IQuillVip: typeof import('~icons/quill/vip')['default']
    NewTask: typeof import('./src/components/dashboard/NewTask.vue')['default']
    PayMoney: typeof import('./src/components/dashboard/PayMoney.vue')['default']
    PayResult: typeof import('./src/components/dashboard/PayResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignModal: typeof import('./src/components/modal/SignModal.vue')['default']
    TaskDetail: typeof import('./src/components/dashboard/TaskDetail.vue')['default']
    TaskDetailLive: typeof import('./src/components/dashboard/TaskDetailLive.vue')['default']
    UserPersona: typeof import('./src/components/dashboard/UserPersona.vue')['default']
    UserProfile: typeof import('./src/components/dashboard/UserProfile.vue')['default']
    VideoResource: typeof import('./src/components/dashboard/VideoResource.vue')['default']
  }
}
